Rename category to catalogue, add setup.py and is_public
django-oscar/django-oscar-odin pull request #2
Opened 2023-09-29 15:05 UTC by viggo-devries

2023-09-30 00:13 UTC, timsavage requested changes
Tests also need to be updated to refer to catalogue.

2023-09-30 00:13 UTC, timsavage commented on setup.py
Please remove this file. This package is using poetry for dependency management building of wheel files.

2023-09-30 00:14 UTC, timsavage commented on setup.py
`poetry build` will generate a wheel and `.tar.gz` source package in the `dist` folder.

2023-10-03 14:04 UTC, viggo-devries commented
@timsavage Please check again.

2024-01-04 13:25 UTC, closed without merging